class Constants():
    """Constants used throughout the game."""

    CARD_SCALE = 0.5
    CARD_WIDTH = 140 * CARD_SCALE
    CARD_HEIGHT = 190 * CARD_SCALE

    POSITION_HEIGHT_HORIZ = 200
    POSITION_WIDTH_HORIZ = 600
    POSITION_HEIGHT_VERT = 400
    POSITION_WIDTH_VERT = 150

    WINDOW_WIDTH = 1024
    WINDOW_HEIGHT = 768